# Generated by Django 4.1 on 2022-08-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PROYECTO', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=50)),
                ('guia', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=80)),
            ],
        ),
    ]
